services:
  db:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_DB: spatial_cms
      POSTGRES_USER: spatial_cms
      POSTGRES_PASSWORD: spatial_cms
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
